// @generated by protobuf-ts 2.11.1 with parameter server_generic
// @generated from protobuf file "protos/private/user/v1/userservice.proto" (package "protos.private.user.v1", syntax proto3)
// tslint:disable
import { GetUserByEmailResponse } from "./userservice";
import { GetUserByEmailRequest } from "./userservice";
import { GetUserByIDResponse } from "./userservice";
import { GetUserByIDRequest } from "./userservice";
import { CreateUserResponse } from "./userservice";
import { CreateUserRequest } from "./userservice";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service protos.private.user.v1.UserService
 */
export interface IUserService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: CreateUser
     */
    createUser(request: CreateUserRequest, context: T): Promise<CreateUserResponse>;
    /**
     * @generated from protobuf rpc: GetUserByID
     */
    getUserByID(request: GetUserByIDRequest, context: T): Promise<GetUserByIDResponse>;
    /**
     * @generated from protobuf rpc: GetUserByEmail
     */
    getUserByEmail(request: GetUserByEmailRequest, context: T): Promise<GetUserByEmailResponse>;
}
