// @generated by protobuf-ts 2.11.1 with parameter server_generic
// @generated from protobuf file "protos/public/auth/v1/authservice.proto" (package "protos.public.auth.v1", syntax proto3)
// tslint:disable
import { RegisterResponse } from "./authservice";
import { RegisterRequest } from "./authservice";
import { LoginResponse } from "./authservice";
import { LoginRequest } from "./authservice";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service protos.public.auth.v1.AuthService
 */
export interface IAuthService<T = ServerCallContext> {
    /**
     * @generated from protobuf rpc: Login
     */
    login(request: LoginRequest, context: T): Promise<LoginResponse>;
    /**
     * @generated from protobuf rpc: Register
     */
    register(request: RegisterRequest, context: T): Promise<RegisterResponse>;
}
